/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://qp3uavhwr5bnvn3cax7cym3lbi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-3qfy5ykbtbfxlecwc2alvjthsm",
    "aws_cognito_identity_pool_id": "us-east-1:bf23ff28-c4b2-4bc7-8e03-f29c4c240638",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4oMC44syS",
    "aws_user_pools_web_client_id": "3nt8kpf8ds28hjvk8bt21an0ll",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "wachow0c380c76c41a480c99ebbcf5e9c55440203036-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
