import AwsProvider from 'providers/AwsProvider'
import './globals.css'
import { HeaderFooterTemplate } from 'components/Organisms/HeaderFooterTemplate'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AwsProvider >
          <HeaderFooterTemplate>
            {children}
          </HeaderFooterTemplate>
        </AwsProvider>
      </body>
    </html>
  )
}
